export default function Step9ActionPlan({ steps, loading, error }) {
  return (
    <div className="step-section" style={{ animationDelay: '640ms' }}>
      <div className="step-header">
        <div className="step-num">9</div>
        <div>
          <div className="step-title">Your Solar Action Plan</div>
          <div className="step-subtitle">Personalized 6-step roadmap generated by Claude AI</div>
        </div>
      </div>

      <div className="card">
        {loading && (
          <div style={{ textAlign: 'center', padding: '40px 0' }}>
            <div className="spinner" />
            <div style={{ color: 'var(--text2)', fontSize: '0.9rem', marginTop: 16 }}>
              Claude is generating your personalized action plan...
            </div>
          </div>
        )}

        {error && (
          <div style={{ padding: '20px', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 10, color: '#fca5a5', fontSize: '0.9rem' }}>
            Could not generate action plan: {error}
          </div>
        )}

        {!loading && !error && steps && (
          <>
            <div style={{ marginBottom: 24, padding: '14px 18px', background: 'linear-gradient(135deg, rgba(245,158,11,0.1), rgba(245,158,11,0.04))', border: '1px solid rgba(245,158,11,0.2)', borderRadius: 10, fontSize: '0.88rem', color: 'var(--text2)', display: 'flex', gap: 10 }}>
              <span>🤖</span>
              <span>
                This personalized action plan was generated by Claude AI using your specific solar analysis data —
                roof dimensions, local energy costs, production estimates, and top installer match.
              </span>
            </div>

            <div className="action-steps">
              {steps.map((step, i) => (
                <div
                  key={step.number || i}
                  className="action-step"
                  style={{ animationDelay: `${i * 80}ms` }}
                >
                  <div style={{ flexShrink: 0 }}>
                    <div className="action-num">{step.number || i + 1}</div>
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6, flexWrap: 'wrap' }}>
                      {step.icon && <span className="action-icon">{step.icon}</span>}
                      <div className="action-title">{step.title}</div>
                    </div>
                    <div className="action-desc">{step.description}</div>
                    {step.timeline && (
                      <div className="action-timeline">{step.timeline}</div>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div style={{
              marginTop: 32, padding: '20px 24px',
              background: 'linear-gradient(135deg, rgba(16,185,129,0.1), rgba(16,185,129,0.04))',
              border: '1px solid rgba(16,185,129,0.2)', borderRadius: 12
            }}>
              <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', color: 'var(--green)', marginBottom: 8 }}>
                Your Impact at a Glance
              </div>
              <div style={{ fontSize: '0.88rem', color: 'var(--text2)', lineHeight: 1.7 }}>
                By following this action plan, you'll join millions of homeowners reducing their carbon footprint while
                building long-term energy independence. Solar is one of the highest-ROI home improvements available —
                and one of the most impactful personal actions you can take for the planet.
              </div>
              <div style={{ marginTop: 14, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                <span className="badge badge-green">Clean Energy</span>
                <span className="badge badge-solar">Financial Independence</span>
                <span className="badge badge-blue">Grid Resilience</span>
                <span className="badge badge-purple">Carbon Neutral</span>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
